[package]
name = "polytile"
version = "0.0.3"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.5.27", features = ["derive"] }
itertools = "0.14.0"
num-bigint = "0.4.6"
pathfinding = "4.14.0"
rayon = "1.6.1"
indicatif = {version = "0.17.3", features = ["rayon"]}
seq-macro = "0.3.5"
graphalgs = "0.2.0"
