[package]
name = "polytile"
version = "0.0.3"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
itertools = "0.10.5"
rayon = "1.6.1"
# indicatif = {version = "0.17.3", features = ["rayon"]}
seq-macro = "0.3.5"